services:
  - type: web
    name: ghost
    env: docker
    autoDeploy: false
    plan: free
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 1 # GB
    envVars:
      - key: database__client
        value: mysql
      - key: database__connection__user
        sync: false
      - key: database__connection__password
        sync: false
      - key: database__connection__host
        sync: false
      - key: database__connection__port
        sync: false
      - key: database__connection__database
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
